name: release
on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  release:
    runs-on: ubuntu-latest
    if: "github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'autorelease: pending')"
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: docker/metadata-action@v4
        if: ${{ steps.release.outputs.release_created }}
        id: meta
        with:
          images: ghcr.io/media-data-hub/media-data-hub
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ steps.release.outputs.tag_name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.release.outputs.tag_name }}
            type=semver,pattern={{major}},value=${{ steps.release.outputs.tag_name }}
      - uses: docker/setup-qemu-action@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: docker/setup-buildx-action@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: docker/login-action@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
